// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMapSystem {
  function genRole(uint32 _age, uint32 _karma, string memory _name, string memory _description) external;
}
